---
port_profiles:
  COMPUTE:
    mode: trunk
    vlans: "2,3,4,2555,2556"
  STORAGE:
    mode: trunk
    vlans: "2556"
  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"
  TENANT_A:
    mode: access
    vlans: "110"
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  POD-1-COMPUTE:
    rack: rack1
    adapters:
      - type: nic
        switch_ports: [Ethernet1, Ethernet2]
        switches: [WL-LEAF1, WL-LEAF2]
        profile: COMPUTE
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF1A]
        profile: TENANT_A
  server02:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF2A]
        profile: TENANT_A
