---
# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  OPENTEXT:
    mac_vrf_vni_base: 10000
    vrfs:
      OPENTEXT_CORP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          30:
            name: Waterloo LAN
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          31:
            vni_override: 50111
            name: Waterloo Finance
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.11.1/24
      Tenant_A_WEB_Zone:
        vrf_vni: 11
        svis:
          120:
            name: Tenant_A_WEB_Zone_1
            tags: [web, erp1]
            enabled: true
            ip_subnet: 10.1.20.0/24
          121:
            name: Tenant_A_WEBZone_2
            tags: [web]
            enabled: true
            ip_address_virtual: 10.1.21.1/24
      Tenant_A_APP_Zone:
        vrf_vni: 12
        svis:
          130:
            name: Tenant_A_APP_Zone_1
            tags: [app, erp1]
            enabled: true
            ip_subnet: 10.1.30.0/24
          131:
            name: Tenant_A_APP_Zone_2
            tags: [app]
            enabled: true
            ip_address_virtual: 10.1.31.254/24
      Tenant_A_DB_Zone:
        vrf_vni: 13
        svis:
          140:
            name: Tenant_A_DB_BZone_1
            tags: [db, erp1]
            enabled: true
            ip_address_virtual: 10.1.40.1/24
          141:
            name: Tenant_A_DB_Zone_2
            tags: [db]
            enabled: true
            ip_address_virtual: 10.1.41.1/24
      Tenant_A_WAN_Zone:
        vrf_vni: 14
        svis:
          150:
            name: Tenant_A_WAN_Zone_1
            tags: [wan]
            enabled: true
            ip_address_virtual: 10.1.40.1/24
    l2vlans:
      160:
        vni_override: 55160
        name: Tenant_A_VMOTION
        tags: [vmotion]
      161:
        name: Tenant_A_NFS
        tags: [nfs]